In [50]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
rarr=arr.reshape(9,2)
print(rarr)
tarr=np.transpose(rarr)
print(tarr)
rarr=arr.reshape(-1)
print(rarr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]]
[[ 1  3  5  7  9 11 13 15 17]
 [ 2  4  6  8 10 12 14 16 18]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [4]:
rarr.flat[5]


6

In [5]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
carr=np.concatenate((arr1,arr2))
carr



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
carr=np.concatenate((arr1,arr2),axis=1)


In [12]:
arr1=np.array(["shivu","paku","goutam","vinay"])
np.sort(arr1)

array(['goutam', 'paku', 'shivu', 'vinay'], dtype='<U6')

In [26]:
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
1
14
15
16
17
18


In [27]:
arr=np.array([10,11,12,13,14,15,26,27,15,29,30,31,32])
x=np.where(arr==15)
x

(array([5, 8], dtype=int64),)

In [36]:
nums=np.array([1,2,3,4,5,6,7,8,9,10])
b=[True,False,True,False,True,False,True,False,True,False]
newarr=nums[b]
newarr

array([1, 3, 5, 7, 9])

In [37]:
evens=np.array(list(filter(lambda n:n%2==0,nums)))
evens

array([ 2,  4,  6,  8, 10])

In [38]:
d=np.array(list(map(lambda n:n*n,evens)))
d

array([  4,  16,  36,  64, 100])

In [40]:
from functools import reduce
res=reduce(lambda n,m:n+m ,d)
res

220

In [41]:
#Mean,Median,Mode
arr=np.array([10,11,12,13,14,15,26,27,15,29,30,31,32])
np.mean(arr)


20.384615384615383

In [43]:
from scipy import stats
stats.mode(arr)

ModeResult(mode=15, count=2)

In [44]:
zeros=np.zeros(5)
#zeros

array([0., 0., 0., 0., 0.])

In [45]:
ones=np.ones(5)
#ones

array([1., 1., 1., 1., 1.])

In [46]:
lins=np.linspace(0,10,10)
#lins

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [48]:
logs=np.logspace(1,10)
logs

array([1.00000000e+01, 1.52641797e+01, 2.32995181e+01, 3.55648031e+01,
       5.42867544e+01, 8.28642773e+01, 1.26485522e+02, 1.93069773e+02,
       2.94705170e+02, 4.49843267e+02, 6.86648845e+02, 1.04811313e+03,
       1.59985872e+03, 2.44205309e+03, 3.72759372e+03, 5.68986603e+03,
       8.68511374e+03, 1.32571137e+04, 2.02358965e+04, 3.08884360e+04,
       4.71486636e+04, 7.19685673e+04, 1.09854114e+05, 1.67683294e+05,
       2.55954792e+05, 3.90693994e+05, 5.96362332e+05, 9.10298178e+05,
       1.38949549e+06, 2.12095089e+06, 3.23745754e+06, 4.94171336e+06,
       7.54312006e+06, 1.15139540e+07, 1.75751062e+07, 2.68269580e+07,
       4.09491506e+07, 6.25055193e+07, 9.54095476e+07, 1.45634848e+08,
       2.22299648e+08, 3.39322177e+08, 5.17947468e+08, 7.90604321e+08,
       1.20679264e+09, 1.84206997e+09, 2.81176870e+09, 4.29193426e+09,
       6.55128557e+09, 1.00000000e+10])

In [49]:
r=np.arange(0,5,2)
#r

array([0, 2, 4])

In [53]:
x=np.random.randint(10,55,(6,3))
x

array([[18, 14, 46],
       [51, 18, 46],
       [40, 12, 22],
       [20, 19, 25],
       [36, 15, 36],
       [53, 35, 37]])

In [54]:
answer=np.array(["ans1","ans2","ans3","ans4"])
np.random.shuffle(answer)
answer

array(['ans3', 'ans1', 'ans4', 'ans2'], dtype='<U4')